### ISSUE TITLE
Creating the main components

### ISSUE THREAD

**Issue by yairtawil** [Webiks/MapMip#2]
Create 3 components (pages) with:

1. Cesium.
2. Leaflet.
3. Ol3.

With navigation option among them, while preserving each component context using URL

**URL context should include:**
- [x]  Map library of use (Cesium / Ol3/ Leaflet).
- [x]  Map center point (geolocation lat long).
- [x]  Zoom level (Lealfet, Ol3).
- [x]  2-d or 3-d view(Cesium).
- [x]  3-d view: camera parameters (Cesium).
- [x] Bounding rectangle.
- [x] Rotation (heading) on 2D views(Cesium MapMode2D, Ol3).
- [x] Markers.
- [x] Tile layer URL.

**Comment by OmKoren** [comment]
Cesium doesn't "know" zoom levels. Because Cesium lives in a 3D world, discrete zoom levels aren't relevant, rather some complex "camera" parameters.
The suggested solution:
1. When launching Cesium allow the URL to also describe camera parameters.
2. Also allow the definition of the ground bounding rectangle inside the URL - in that way the user / developer doesn't have to know the internal details of every javascript library (Cesium/OL3/Leaflet), he can simply pass the bounding box and get the right view.

**Comment by OmKoren** [comment]
@yairtawil Another parameter that we want to add to the URL is a single marker. Very important context-preserving-wise.
Let's just add this as an another optional parameter. The marker can have lon/lat or lon/lat/alt. A relevant billboard (cesium) or marker (leaflet) or feature (OL3) should be displayed.

**Comment by yairtawil** [comment]
- [ ] Rotation (heading) on 2D views(Cesium MapMode2D, Ol3)

Cesium MapMode2D and Ol3 should save rotation on context. 
when the  following actions will happen:

1. All map moving on Ol3 map will save the  **rotation** ('heading' parameter) on URL.
2. Refresh when state is Ol3 will show the map view with correct **rotation**.
3. Navigate from Ol3 to Cesium will save the correct **rotation**.
4. Navigate from Cesium to Ol3 will save the correct **rotation**.
5. When navigate from Ol3 to Leaflet, before leaving Ol3 the camera will go north by animation**.  
** the reason is, Leaflet lack the option of rotation. (edited)

**Comment by yairtawil** [comment]
- [ ] Marker.

All maps should save markers on context.

- Add markers to map when markers added to URL .
- Remove markers from map when markers removed from URL.
- Allow to parse markers from URL with lat and lng only or lat, lng and height.

**Comment by yairtawil** [comment]
- [x] Tile layer.

All maps should save layers on context.

- Add layers to map when layers added to URL .
- Remove layers from map when layers removed from URL.
- Parsing layers as array of objects from URL(string) by 'rison'( https://github.com/Nanonid/rison ).
