### ISSUE TITLE
Launch an online demo app

### ISSUE THREAD

**Issue by OmKoren** [Webiks/MapMip#3]
Launch a hosted online demo MapMip app.
MapMip is a research project, still in progress (very beginning),
The demo app will be very basic and will probably still have bugs, but it is important that we'll have from the beginning a demo app the goes side by side with the development process. Every important commit should be also pushed to the online demo app.

**Comment by yairtawil** [comment]
MapMip: An angular 2 module on top of CesiumJS, LeafletJS and OpenLayers3. http://mapmip.webiks.com/

Close

**Comment by yairtawil** [comment]
MapMip: An angular 2 module on top of CesiumJS, LeafletJS and OpenLayers3. http://mapmip.webiks.com/

Done.
