### ISSUE TITLE
Compile issue involving @angular/material

### ISSUE THREAD

**Issue by chriswilley** [Webiks/MapMip#64]
Since angular/material 2.0.0-beta.12, the "md" prefix has been replaced with "mat". This prevents MapMip from compiling with `ng serve` or `ng build`. To fix it, change the "MdInputModule" reference to "MatInputModule" in src/app/app.module.ts and src/app/map-mip/components/position-form/position-form.module.ts. Also need to change src/app/map-mip/components/position-form/position-form.component.html like so:

```
<md-input-container color="primary">
    <input mdInput placeholder="{{key}}" [(ngModel)]="params[key].val"
        [ngModelOptions]="{standalone: true}">
</md-input-container>
```

to:
```
<mat-input-container color="primary">
    <input matInput placeholder="{{key}}" [(ngModel)]="params[key].val"
        [ngModelOptions]="{standalone: true}">
</mat-input-container>
```

See [this SO post](https://stackoverflow.com/questions/46666677/angular-material-mdinput-to-matinputmodule) for more info.

**Comment by yairtawil** [comment]
Closed via #66 
Thanks @chriswilley 👍
